### ISSUE TITLE
Viewing POST Request

### ISSUE THREAD

**Issue by josteph** [aschmelyun/larametrics#10]
Hello, thanks for the great package!

I recently encountered following error:
```
"Undefined index: referer (View: /vendor/aschmelyun/larametrics/src/resources/views/requests/show.blade.php)"
```

When trying to access `POST` type request. But viewing `GET` type request works fine.

**Comment by 0xK4d1r** [comment]
Hey,

Last night #7 was merged to fix this issue but it is not released yet. You can point to `dev-master` in `composer.json` to get it.

**Comment by josteph** [comment]
@vjolenz Thank you!
