### ISSUE TITLE
[Question] Difference to Telescope

### ISSUE THREAD

**Issue by johannesschobel** [aschmelyun/larametrics#11]
Dear @aschmelyun ,

i recently stumbled upon this package and was wondering what the difference between `larametrics` and the newly released `laravel telescope` is. Maybe you can describe the key differences?

All the best

**Comment by aschmelyun** [comment]
Hey @johannesschobel, 

I've been asked this a few times and I'll try to give a pretty succinct answer: Larametrics is aimed toward simplicity, compatibility, and use on production systems.

I feel like Laravel Telescope is a great tool to accompany a dev environment, but Larametrics was built to fill a need that I had to monitor my side projects and alert me when something went wrong.

I wanted something self-hosted, easy to set up, and able to be used on some of my 5.6 and lower projects. I think I've created something worthwhile in that, and while it may on the surface look like a cheaper version of Telescope I think we both shine in our own light.

**Comment by johannesschobel** [comment]
Dear @aschmelyun ,

thank you for your detailed answer for my question. For me it wasn't that clear, that is meant to be used for "production mode" - while "telescope" clearly tackles the "development mode". Thanks for pointing that out!

All the best

**Comment by anthonyvancauwenberghe** [comment]
Taylor clearly stated that telescope is also meant to be used in production. Your package comes at an unfortunate time :(

**Comment by aschmelyun** [comment]
Agreed, but I feel like it comes with an "if you really want to, you can" feeling, as it's branded as a debug tool. Whereas I've tried to develop Larametrics as lightweight and meant to run alongside both development and production systems, something like your own version of Sentry.io. 

Timing could have been better on this definitely, you're not wrong, but I feel like there's enough of a difference between us that we can continue to build up in our own ways.

**Comment by nowendwell** [comment]
I think the biggest difference for me, between Telescope and Larametrics, is the compatibility with older versions. I don't always have the resources to keep every single project updated to the latest and greatest Laravel version.

In my opinion, to have a package that provides some of the same features and has the compatibility that it does, makes Larametrics more valuable than Telescope. 

With that said, if Telescope were to expand their compatibility to older versions, I would probably use it instead, but it seems [highly unlikely.](https://github.com/laravel/telescope/issues/65)

**Comment by troyporter** [comment]
> I think the biggest difference for me, between Telescope and Larametrics, is the compatibility with older versions. I don't always have the resources to keep every single project updated to the latest and greatest Laravel version...

I agree here....i was disappointed to see Telescope was only available for 5.7.  But then i wonder if they did that deliberately to be graceful and not to 'kill' already existing packages that do similar things.

In any case, Larametrics has its place in my books ! .. Good job

**Comment by HDVinnie** [comment]
@deviouspk where did he say that? Last I saw they said its meant for dev environment only. While it could be used in production its not recommended.

**Comment by niladam** [comment]
I'll be off-topic, but i need to provide me opinion.

I haven't had the chance to try this **yet**, but i'm planning on testing it sometimes next week.

Personally, i think that having a large number of packets that basically do the same thing is really a **good** thing for the entire community, and for all the developers (users and creators alike) involved. 

There's no golden rule for doing anything and no golden rule for the 'best' package. Some fit your needs, some don't.

I want to **THANK YOU** for the work you did on this package and i can't stress enough how happy i am to see many alternative packages.

M.
