### ISSUE TITLE
LarametricsModel create function

### ISSUE THREAD

**Issue by josteph** [aschmelyun/larametrics#12]
The following command assumes that the model has `id` column as the primary key, while it can be generic sometimes, such as `user_id` or `uuid`.

```
$larametricsModel = LarametricsModel::create([
                'model' => get_class($event),
                'model_id' => $event->getAttributes()['id'],
                ...
]);
```
It will produce `Undefined index: id` error.

**Comment by Turboveja** [comment]
It seems to happen everytime it tries to get the models. For example, at metrics/models, if you want to try to access to the information it crashes if it saved before the "original model" with an id different from 'id'

**Comment by josteph** [comment]
It would be helpful to use `$event->getKeyName()` than `$event->getAttributes()['id']`.

**Comment by Turboveja** [comment]
I just pulled this, but it happens in every view when it tries to draw the data from the database json column 'original'.

**Comment by josteph** [comment]
I also notice this issue if the request comes from authenticated user (guest).

**Comment by aschmelyun** [comment]
Try this out now with the latest changes in `master`. I've converted all of the references using an `['id']` attribute in the model service provider and pages to use `getKey()` and `getKeyName()`.
