### ISSUE TITLE
Customize Email

### ISSUE THREAD

**Issue by bishalkc** [aschmelyun/larametrics#14]
Can we add the config values for EMAIL Subject?
<img width="645" alt="screen shot 2018-10-30 at 2 05 17 pm" src="https://user-images.githubusercontent.com/5494719/47740012-1b18c200-dc4d-11e8-9aa7-3580b24c958c.png">

**Comment by aschmelyun** [comment]
Hi @bishalkc,

Per commit c9093956ea5bd627ff11f926126b3abc7a29b3f9 you can now customize your email alert subjects and sender name/emails using the following variables in your `.env` file:

- `LARAMETRICS_LOG_SUBJECT` - The subject of emails alerting you when a log is written
- `LARAMETRICS_MODEL_SUBJECT` - The subject of emails alerting you when a model has been changed
- `LARAMETRICS_ROUTE_SUBJECT` - The subject of emails alerting you to a route requested
- `LARAMETRICS_FROM_EMAIL` - The email address displayed as the sender of the alert emails
- `LARAMETRICS_FROM_NAME` - The name displayed as the sender of the alert emails

All of these are optional, not setting them will result in the default subjects that were already present on the package.
