### ISSUE TITLE
SQL error using social login

### ISSUE THREAD

**Issue by bishalkc** [aschmelyun/larametrics#15]
I see SQLSTATE[22001] in logs when trying to insert into larametrics_requests table using social login uri. 
<img width="1185" alt="screen shot 2018-10-30 at 2 08 06 pm" src="https://user-images.githubusercontent.com/5494719/47740147-79de3b80-dc4d-11e8-927d-23c5e3d3565e.png">

**Comment by aschmelyun** [comment]
Seems like it's due to the `uri` column using a 255-character varchar field. Maybe I should modify this to a text field, instead? Could do a higher limit varchar, but if someone's running MySQL < 5.0.3 that won't be valid.

**Comment by nowendwell** [comment]
+1 for TEXT field
[Max realistic length of a URL is 2048](https://stackoverflow.com/a/417184) which is much longer than your standard VARCHAR 255 field.
