### ISSUE TITLE
Switch Out Controller Imports

### ISSUE THREAD

**Issue by ghost** [aschmelyun/larametrics#16]
Package controllers should import `Illuminate\Routing\Controller` as opposed to `App\Http\Controllers\Controller`

If the given user has moved their `Controller` class, or has changed the namespace of the application away from `App` then this package fails completely.

As of now I'll need to fork this and change all these references in order to use it, a package like this should never depend on classes in the `app` directory, because there's simply no way to know how the user has their app configured.

**Comment by aschmelyun** [comment]
Thanks for catching that! A pr with those changed would be a massive help.
