### ISSUE TITLE
Call to undefined method App\Support\Database\Builder::getChanges()

### ISSUE THREAD

**Issue by nowendwell** [aschmelyun/larametrics#2]
Get an error on user logout when watching the App\User model.

The Application tries to refresh the rememberToken on user logout and fails.

vendor/aschmelyun/larametrics/src/LarametricsModelServiceProvider.php:65

Laravel version: 5.3.31
Larametrics version: dev-master

**Comment by nowendwell** [comment]
Upon further digging, this is caused on any model edit from calling getChanges() which was introduced in Laravel 5.5

An alternative for older versions is getDirty() which does almost identically the same thing.

**Comment by aschmelyun** [comment]
Fixed with #6. getDirty() is also available in Laravel 4.2, so this helps bring compatibility to lower versions! Thanks!
