### ISSUE TITLE
Cannot redeclare uses() error

### ISSUE THREAD

**Issue by dellow** [aschmelyun/larametrics#23]
Hi,

I get this error when I clear the config cache in my application:    

    In web.php line 70:
    Cannot redeclare uses() (previously declared in 
    vendor/aschmelyun/larametrics/src/routes/web.php:68)

**Comment by josteph** [comment]
Hello @sdellow 

Yeah I couldn't cache the routes if using the package's routes file.

For the workaround, I created my own routes called `larametrics.php`, with content like:
```
Route::prefix('admin')->name('larametrics::')->group(function() {
    // dashboard routes
    Route::get('/metrics', 'MetricsController@index')->name('metrics.index');
    
    ...
});
```

**Comment by dellow** [comment]
Nice, I'll have to do this if it doesn't get fixed natively. Thanks.

**Comment by dellow** [comment]
Sorry this still isn't fixed:

`Cannot redeclare larametricsUses() (previously declared in vendor/aschmelyun/larametrics/src/routes/web.php:68)`
