### ISSUE TITLE
logsWatched config doesn't stop logs being recorded

### ISSUE THREAD

**Issue by dellow** [aschmelyun/larametrics#24]
Hi,

If I set the `logsWatched` config value to false it doesn't actually stop anything being recorded in the database. It does change the dashboard index view to "Latest Model Changes" instead of "Latest Log Changes" but that's all it does.

**Comment by josteph** [comment]
`php artisan config:clear` ?

**Comment by dellow** [comment]
Tried it. `logsWatched` doesn't seem to do anything except update the views:

https://github.com/aschmelyun/larametrics/search?q=logsWatched&unscoped_q=logsWatched

**Comment by aschmelyun** [comment]
Fixed in PR #31
