### ISSUE TITLE
Can we exclude some requests to specific routes?

### ISSUE THREAD

**Issue by tanmuhittin** [aschmelyun/larametrics#25]
We can exclude larametrics requests but what if we would like to exclude some other requests.
Like LOGIN requests where we should not log users' password?

**Comment by nowendwell** [comment]
Could do something similar to what the Laravel Middlewares use.

```
Middleware
protected $except = [
    'stripe/*',
];

Larametrics
'requestsToIgnore' => [
    'login/*',
    'reset-password/*',
    'etc'
]
```

We could add it to the config and then allow the user to set their specific routes to skip there.
Then we could check against that in the LarametricsRouteServiceProvider.php:40 using the Request::is() function (keeping with the Laravel 4.2 compatibility).

I'll put together a PR and see if we can get this added.

**Comment by nowendwell** [comment]
Added PR #26

**Comment by aschmelyun** [comment]
PR #26 merged
