### ISSUE TITLE
Install on Lumen

### ISSUE THREAD

**Issue by nowendwell** [aschmelyun/larametrics#28]
I would love to use this on Lumen to get an overall snapshot of how my API is being used.
We would need to change quite a bit of the ServiceProvider in order to "install" it in a Lumen environment. Other packages (like barryvdh/laravel-debugbar) use a LumenServiceProvider for install.

This is a big feature request so not expecting any immediate movement. I am glad to help to need to figure out how to install Lumen packages first.

**Comment by aschmelyun** [comment]
This is a good idea. Additionally could add in a suite of artisan commands to display data as an alternate to a dashboard. Since Lumen is (usually) used as purely an API.

**Comment by salvationarinze** [comment]
Hi, is this still a possibility?
