### ISSUE TITLE
ErrorException thrown with message "strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Mohammed-Daud** [aschmelyun/larametrics#30]
ErrorException thrown with message "strlen() expects parameter 1 to be string, array given (View: /var/www/app/vendor/aschmelyun/larametrics/src/resources/views/models/model.blade.php)"

Stacktrace:
63 ErrorException in /var/www/app/storage/framework/views/f2f7220de6dd744bad0044effb02ec116874f5a4.php:42
62 ErrorException in /var/www/app/storage/framework/views/f2f7220de6dd744bad0044effb02ec116874f5a4.php:42
61 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/app/storage/framework/views/f2f7220de6dd744bad0044effb02ec116874f5a4.php:42
60 include in /var/www/app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
59 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
58 Illuminate\View\Engines\CompilerEngine:get in /var/www/app/vendor/laravel/framework/src/Illuminate/View/View.php:142
57 Illuminate\View\View:getContents in /var/www/app/vendor/laravel/framework/src/Illuminate/View/View.php:125
56 Illuminate\View\View:renderContents in /var/www/app/vendor/laravel/framework/src/Illuminate/View/View.php:90
55 Illuminate\View\View:render in /var/www/app/vendor/laravel/framework/src/Illuminate/Http/Response.php:42
54 Illuminate\Http\Response:setContent in /var/www/app/vendor/symfony/http-foundation/Response.php:202
53 Symfony\Component\HttpFoundation\Response:__construct in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:747
52 Illuminate\Routing\Router:toResponse in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:719
51 Illuminate\Routing\Router:prepareResponse in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:679
50 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/zizaco/entrust/src/Entrust/Middleware/EntrustRole.php:42
48 Zizaco\Entrust\Middleware\EntrustRole:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
45 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
42 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
33 Illuminate\Session\Middleware\StartSession:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
24 Illuminate\Pipeline\Pipeline:then in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
23 Illuminate\Routing\Router:runRouteWithinStack in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:656
22 Illuminate\Routing\Router:runRoute in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:622
21 Illuminate\Routing\Router:dispatchToRoute in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:611
20 Illuminate\Routing\Router:dispatch in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/fideloper/proxy/src/TrustProxies.php:57
17 Fideloper\Proxy\TrustProxies:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
2 Illuminate\Pipeline\Pipeline:then in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
0 Illuminate\Foundation\Http\Kernel:handle in /var/www/app/public/index.php:55

**Comment by aschmelyun** [comment]
Could you provide me with the data in the `original` and `changes` columns in the row for the particular larametrics_model you're trying to view? Unless this is thrown from the dashboard, then please just choose one object and provide me with the data above if you can.

Additionally, what version of Laravel are you running?

**Comment by Turboveja** [comment]
Hi, this happens when you insert in the database a model with dates. 

The dates inserted are array, not string. (from Carbon I think)

For example, I created a model (CallcenterCall), which has column date:

![image](https://user-images.githubusercontent.com/17595471/48131238-acacb300-e28f-11e8-809f-b52992a5767c.png)

So, in the models\model.blade.php Line 42

![image](https://user-images.githubusercontent.com/17595471/48131256-c1894680-e28f-11e8-96ba-b0d9449eeb7d.png)

We are doing strlen() with an array, and not with a string.

**Comment by andrey-kosinov** [comment]
This happened to me after upgrading Laravel to version 5.7.12

**Comment by aschmelyun** [comment]
This should be fixed with PR #42
