### ISSUE TITLE
Undefined index: referer

### ISSUE THREAD

**Issue by ovaisahmed43** [aschmelyun/larametrics#34]
![image](https://user-images.githubusercontent.com/9747881/47915838-ef544100-dec5-11e8-8810-a9e68e6c2a8d.png)

At
(<project>/vendor/aschmelyun/larametrics/src/resources/views/requests/show.blade.php)

When i hit
![image](https://user-images.githubusercontent.com/9747881/47915918-30e4ec00-dec6-11e8-8a3b-e354634c91a6.png)

**Comment by 0xK4d1r** [comment]
Hi,

It was fixed couple days ago with #7 and the **1.1.0**  release includes it. I tried and could not reproduces the error now. Could you check that you are at least using **1.1.0**?
