### ISSUE TITLE
Couple Notices

### ISSUE THREAD

**Issue by EdvardasP** [aschmelyun/larametrics#40]
Hello,

Couple notices while testing this package.
1) 404 error pages not logged, for example domain.com/adsasdas return 404, but is not catched by Request. Is it expected?
2) Would be great, if Models log user ID who made changes.
3) In models change page special characters are stripped and Lithuania letters do not appear. For example:
instead of hello**Š** I see hello. I found, that by removing function htmlspecialchars() helps to fix this.
In resources/views/models/show.blade.php 39 and 59 lines.
4) Also, would be great to have pop-up asking, if you are sure for Reverting changes.

Do not want to spam tracker, therefore opened one issue.

**Comment by aschmelyun** [comment]
For 1, 404 error pages being logged is something that's in the works now. 2 and 4 sound like great additions, and I'll be sure to test out 3 as well! 

Thanks for your suggestions!

**Comment by aschmelyun** [comment]
All of these have been added into Larametrics as of v1.2. 404 pages are now logged, the user ID of an authenticated user is logged alongside model changes, special characters are no longer stripped out of model changes pages, and there's now a pop-up confirming that you want to revert DB changes.
