### ISSUE TITLE
Class Aschmelyun\Larametrics\LarametricsModelServiceProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register)

### ISSUE THREAD

**Issue by zmaglica** [aschmelyun/larametrics#41]
Hello,

I am trying to install larametrics on Laravel 5.2 (php 7.1) and I am getting this error:

`Class Aschmelyun\Larametrics\LarametricsModelServiceProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register)`

I am not sure how to fix this issue... Is there a solution how to fix this problem?

Best regards.

**Comment by nowendwell** [comment]
Switching to "dev-master" should clear this up. This will be resolved in the next tagged version.

**Comment by aschmelyun** [comment]
Exactly what @nowendwell said, I'll make a note to get tagged versions out on a more regular basis.
