### ISSUE TITLE
Undefined index: referer vendor/aschmelyun/larametrics/src/resources/views/requests/show.blade.php

### ISSUE THREAD

**Issue by pedrogaldino** [aschmelyun/larametrics#49]
This happens when i click in to view details of request.

The request has been made from an Media player. I think the media player don't send this header field on the request.

This can be solved with an isset in that view?

Version: "aschmelyun/larametrics": "^1.1"
Laravel: 5.7
PHP: 7.3

**Comment by namnv609** [comment]
@pedrogaldino @aschmelyun: Please review my PR :smiley:!
