### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by toocool** [aschmelyun/larametrics#51]
There is no issue, just wanted to say good job and I like your package.
But I have a feeling that it is starting to be abandoned, or is it just me?

**Comment by aschmelyun** [comment]
I'm glad you like it! And it's not just you, the last few months I've been caught up in a few different things and some life transitions, so the project fell by the wayside a little bit. 

However, I'm planning on making more time soon to introduce new and useful features to the package, tend to the open pull requests, and answer any outstanding issues. 

If you'd like to see the (very basic) roadmap I have planned, I've made a Trello board specifically for it: https://trello.com/b/JXhznGIv/larametrics
