### ISSUE TITLE
Class 'Aschmelyun\Larametrics\Larametrics' not found

### ISSUE THREAD

**Issue by MrFallen** [aschmelyun/larametrics#52]
Hello guys! Who can help me?
![image](https://user-images.githubusercontent.com/5339386/58429749-3451f600-80ea-11e9-817b-95271b78b039.png)

**Comment by nowendwell** [comment]
Looks like the service provider isn't loaded. Double check your config/app.php to make sure it's in the providers array.

**Comment by MrFallen** [comment]
> Looks like the service provider isn't loaded. Double check your config/app.php to make sure it's in the providers array.

I added the necessary line and such error appeared.
![image](https://user-images.githubusercontent.com/5339386/58431559-c0b3e700-80f1-11e9-9776-9653fb453160.png)

**Comment by MrFallen** [comment]
![image](https://user-images.githubusercontent.com/5339386/58431625-fc4eb100-80f1-11e9-9842-695e7c0e65e0.png)
![image](https://user-images.githubusercontent.com/5339386/58431645-0f618100-80f2-11e9-85c3-a0ffb719a783.png)

**Comment by MrFallen** [comment]
Laravel 5.6 I have no problems on Localhost, but there are problems when I install on a hosting.

**Comment by nowendwell** [comment]
Run `composer dump-autoload` to clear your cache. That should grab it.

Laravel 5.5+ has the ability to automatically "discover" packages. Double check your hosting Laravel version.

**Comment by MrFallen** [comment]
> Run `composer dump-autoload` to clear your cache. That should grab it.
> 
> Laravel 5.5+ has the ability to automatically "discover" packages. Double check your hosting Laravel version.

![image](https://user-images.githubusercontent.com/5339386/58560016-9ab05300-8267-11e9-8a3b-c60fb99ab367.png)
Did not help. :( I just copied my local project and uploaded to the hosting.

**Comment by nowendwell** [comment]
If the package wasn't discovered, it probably isn't in your composer file.

Glad you found a workaround for it.

**Comment by MrFallen** [comment]
> If the package wasn't discovered, it probably isn't in your composer file.
> 
> Glad you found a workaround for it.

You misunderstood me, the problem is not solved :(

Is this composer file?
![image](https://user-images.githubusercontent.com/5339386/58577121-238bb680-8289-11e9-89e9-72d7c6904774.png)

**Comment by aschmelyun** [comment]
Hey @MrFallen, can you run the following command from your app's root and let me know what the output is?

`composer remove aschmelyun/larametrics && composer require aschmelyun/larametrics`

I've just tried installing the package on Laravel 5.6, 5.7, and 5.8 versions and all of them discovered the package at the end of the composer update running.

**Comment by MrFallen** [comment]
> Hey @MrFallen, can you run the following command from your app's root and let me know what the output is?
> 
> `composer remove aschmelyun/larametrics && composer require aschmelyun/larametrics`
> 
> I've just tried installing the package on Laravel 5.6, 5.7, and 5.8 versions and all of them discovered the package at the end of the composer update running.

Hosting:
![image](https://user-images.githubusercontent.com/5339386/58631512-24bef100-8326-11e9-8da0-d2f1479626eb.png)
Localhost:
![image](https://user-images.githubusercontent.com/5339386/58631844-2341f880-8327-11e9-85d1-07ed718c1b3c.png)
![image](https://user-images.githubusercontent.com/5339386/58631980-8f246100-8327-11e9-8b0b-8707a107b9de.png)

**Comment by aschmelyun** [comment]
Looks like it's an issue with Composer not having enough memory to complete its install. The recommended amount is 1GB, or 512MB physical and 512MB swap.

**Comment by MrFallen** [comment]
> Looks like it's an issue with Composer not having enough memory to complete its install. The recommended amount is 1GB, or 512MB physical and 512MB swap.

Now I am upgrade hosting to VDS.
![image](https://user-images.githubusercontent.com/5339386/58757554-5a93ed80-8551-11e9-99ec-8d11c2b03aa9.png)



> Hey @MrFallen, can you run the following command from your app's root and let me know what the output is?
> 
> `composer remove aschmelyun/larametrics && composer require aschmelyun/larametrics`
> 
> I've just tried installing the package on Laravel 5.6, 5.7, and 5.8 versions and all of them discovered the package at the end of the composer update running.

![image](https://user-images.githubusercontent.com/5339386/58757575-bfe7de80-8551-11e9-9c66-4a1202959209.png)

**Comment by MrFallen** [comment]
Idk what's happened but Larametrics works!
