### ISSUE TITLE
Laravel 6 requires laravel/helpers

### ISSUE THREAD

**Issue by camerontucker** [aschmelyun/larametrics#54]
str_contains() and other helpers are now optional in Laravel 6. Could simply update the docs to say laravel/helpers is required for v6+.

"All str_ and array_ helpers have been moved to the new laravel/helpers Composer package and removed from the framework. If desired, you may update all calls to these helpers to use the Illuminate\Support\Str and Illuminate\Support\Arr classes. Alternatively, you can add the new laravel/helpers package to your application to continue using these helpers:

composer require laravel/helpers"

[https://laravel.com/docs/6.x/upgrade#helpers](https://laravel.com/docs/6.x/upgrade#helpers)

**Comment by felixdorn** [comment]
I ran into the same issue, would be good to add a notice in the documentation. 
Moreover, i don't know is this could be reliable but maybe proxiing the used functions so, if `Illumintate\Support\(Str|Arr)` is available we use that, if not we use `str_contains`,...

I could submit a PR.

**Comment by aschmelyun** [comment]
laravel/helpers is now included in the package as of v1.2!
