### ISSUE TITLE
Documentation does not say anything about LARAMETRICS_FROM_EMAIL

### ISSUE THREAD

**Issue by thiagolcks** [aschmelyun/larametrics#56]
I've just updated the project and got +7k errors because of the new default FROM email that is alerts@larametrics.com, and I don't have this email registered in my SES account as a sender.

Searching in the code I've found that now I can customize the sender email using the env variable LARAMETRICS_FROM_EMAIL. I couldn't find anything about it in the documentation.

Besides that, I think it should be a config and not just an env variable.

**Comment by thiagolcks** [comment]
If it is not in the config file it won't work in the production file. I've just had to disable the email notifications because it was still trying to send via alerts@larametrics.com even after changing the .env and clearing the config cache.

**Comment by aschmelyun** [comment]
I've added several references to possible .env values that you can set for the email sending functionality. You can view them on the main package's readme, or on this page of the docs: https://larametrics.com/docs/config-reference.html
