### ISSUE TITLE
Allow to publish views like config, migrations 

### ISSUE THREAD

**Issue by felixdorn** [aschmelyun/larametrics#57]
Awesome work !

I would like to customize a bit the UI, like adding custom panels that redirect to somewhere else but i can't find out how to modify these views as i can not publish them ?

Is this a wanted behavior ?

Félix

**Comment by aschmelyun** [comment]
Not sure if this is a wanted behavior, but I'll leave this open in case anyone else has a similar opinion about it. If you want to add/view the templates directly that make up the admin panel for Larametrics, you can see them all in `vendor/aschmelyun/larametrics/resources/views`.
