### ISSUE TITLE
Watching 404 Requests

### ISSUE THREAD

**Issue by 0xK4d1r** [aschmelyun/larametrics#8]
Hey,

I need to track 404 requests but with this architecture it does not seem to be possible because the callback given to `Route::matched` only executed when route exists. I guess watching 404s can be supported using middleware. What do you think? Would you accept if I pr for it?

Thanks

**Comment by aschmelyun** [comment]
Instead of `Route::matched` there's also https://laravel.com/api/5.6/Illuminate/Foundation/Http/Events/RequestHandled.html, although it looks like it's only available in Laravel 5.4+. I'd accept a pr as long as it wouldn't affect any of the standard functionality.

**Comment by 0xK4d1r** [comment]
Right, I did some digging but couldn't find this event. I'm gonna pr for it asap :) Thanks

**Comment by 0xK4d1r** [comment]
What do you think on extracting the logic to listener and register it via `EventServiceProvider?`. Also the logics in the other providers could be extracted like that too.

**Comment by aschmelyun** [comment]
Are you talking about extracting out the logic in the service providers (e.g. `LarametricsLogServiceProvider`) and instead extending the `EventServiceProvider` class?

**Comment by 0xK4d1r** [comment]
What I meant is extracting out the logic in the service providers to individual listeners (e.g `RecordRequest`, `RecordLog` etc) and registering them in `EventServiceProvider`

**Comment by 0xK4d1r** [comment]
ping @aschmelyun

**Comment by aschmelyun** [comment]
Sounds like a good idea instead of having multiple service providers spread out. We could also group/namespace them in a 'Listeners' or 'Recorders' folder.

**Comment by 0xK4d1r** [comment]
Yeah this is what Im thinking. I will work on that

**Comment by aschmelyun** [comment]
Added a catch-all route in v1.2 that allows you to monitor and log 404 errors!
